[local]
localhost

[mongodb]
mongodb.arrud.online

[redis]
redis.arrud.online

[mysql]
mysql.arrud.online

[rabbitmq]
rabbitmq.arrud.online

[catalogue]
catalogue.arrud.online

[user]
user.arrud.online

[cart]
cart.arrud.online

[shipping]
shipping.arrud.online

[payment]
payment.arrud.online

[frontend]
frontend.arrud.online